spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:prog-local;MODE=MySQL
    username: user
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
    hibernate:
      ddl-auto: create
